---
- name: Install Node.js (npm plus all its dependencies).
  dnf: name=npm state=present enablerepo=epel

- name: Install npm modules required by our app.
  npm: name={{ item }} global=yes state=present
  with_items: "{{ node_npm_modules }}"

- name: Install forever module (to run our Node.js app).
  npm: name=forever global=yes state=present